Readability and organization improvements

diff --git a/Bash/1. Leisure/leisure b/Bash/1. Leisure/leisure
--- a/Bash/1. Leisure/leisure
+++ b/Bash/1. Leisure/leisure
@@ -2,15 +2,78 @@
 # Author: Jacob Niemeir <nniemeir@protonmail.com>
 # Consolidate media library browsing using fzf
 
-LEISURE_VERSION="1.9.8"
+LEISURE_VERSION="2.0"
 
 SUPPORTED_RUNNERS="BlastEm\nbsnes\nDeSmuME\nDolphin\nFlycast\nHeroic\nLutris\nmGBA\nNestopia\nPCSX2\nPPSSPP\nRPCS3\nSteam"
+
+main() {
+	command -v fzf >/dev/null 2>&1 || {
+		echo >&2 "Error: fzf not found"
+		exit 1
+	}
+
+	config_dir="$HOME/.config/leisure/"
+	disable_previews=0
+
+	if [[ "$TERM" != *"kitty"* ]]; then
+		disable_previews=1
+	fi
+
+	process_args "$@"
+
+	games_csv_path="$config_dir/games.csv"
+
+	if ! [ -f "$games_csv_path" ]; then
+		echo "games.csv not found."
+		exit 1
+	fi
+
+	source "$config_dir/paths.conf" || {
+		echo "Error: No configuration file found."
+		exit 1
+	}
+
+	prompt_media_type
+
+	exit 0
+}
+
+process_args() {
+	while getopts "c:hnv" flag; do
+		case $flag in
+		c)
+			config_dir="$OPTARG"
+			;;
+		h)
+			echo "Usage: leisure [options]"
+			echo "Options:"
+			echo "  -c <directory>          Specify a configuration directory"
+			echo "  -h                      Display this message"
+			echo "  -n                      Disable preview images"
+			echo "  -v                      Display version number"
+			exit 0
+			;;
+		n)
+			disable_previews=1
+			;;
+		v)
+			echo "Leisure $LEISURE_VERSION"
+			exit 0
+			;;
+		\?)
+			exit 1
+			;;
+		esac
+	done
+}
 
 fzf_prompt() {
 	local library_files="$1"
 	local show_selection="$2"
+
 	export show_selection
 	export config_dir
+
 	local selection
 	if [ "$disable_previews" -eq 1 ]; then
 		selection=$(echo -e "$library_files" | xargs -I {} basename "{}" | sed 's/\.[^.]*$//' | fzf --height=80% --delimiter ';' --layout=reverse --cycle)
@@ -36,11 +99,13 @@ fzf_prompt() {
                 img_cols=$((terminal_cols*80/100))
                 img_rows=$((terminal_rows*80/100))
             fi
+
             if [ -z "$show_selection" ]; then
                 preview_file=$config_dir/previews/{}.png
             else
                 preview_file=$config_dir/previews/$show_selection.png
             fi
+			
             if [[ -f $preview_file ]]; then
                 kitty icat --clear --transfer-mode=stream --stdin=no --place=${img_cols}x${img_rows}@$(((cols-img_cols)/2))x$(((rows-img_rows)/2)) $preview_file
             else
@@ -53,6 +118,7 @@ fzf_prompt() {
 
 prompt_media_type() {
 	clear
+
 	local media_sections=""
 	[ -d "${BOOKS_PATH}" ] && media_sections="$media_sections Books\n"
 	[ -d "${MOVIES_PATH}" ] && media_sections="$media_sections Films\n"
@@ -62,8 +128,10 @@ prompt_media_type() {
 		echo "No valid media paths found, check your configuration."
 		exit 1
 	fi
+
 	local type_selection
 	type_selection=$(fzf_prompt "$media_sections")
+
 	case "$type_selection" in
 	Books) prompt_books ;;
 	Films) prompt_films ;;
@@ -108,30 +176,16 @@ prompt_films() {
 }
 
 prompt_runner() {
-	local unavailable_runners=""
-	for runner in $(echo -e "$SUPPORTED_RUNNERS"); do
-		if [[ ! $(enumerate_runners "$runner") ]]; then
-			local unavailable_runners="$unavailable_runners$runner"
-		fi
-	done
-
-	local available_runners=""
-	for runner in $(echo -e "$SUPPORTED_RUNNERS"); do
-		if [[ ! "$unavailable_runners" =~ $runner ]]; then
-			local available_runners
-			available_runners="$available_runners$runner\n"
-		fi
-	done
-
-	local available_runners
-	available_runners=$(echo -e "$available_runners" | sed -e '$!b' -e '/^\n*$/d')
-	local available_runners_display
-	available_runners_display="All\n$available_runners"
 	local finished="0"
 	while [ $finished == "0" ]; do
+		local available_runners
+		available_runners=$(get_available_runners)
+
+		local available_runners_list
+		available_runners_list="All\n$available_runners"
 
 		local runner_selection
-		runner_selection=$(fzf_prompt "$available_runners_display")
+		runner_selection=$(fzf_prompt "$available_runners_list")
 		if [ -z "$runner_selection" ]; then
 			clear
 			prompt_media_type
@@ -141,28 +195,11 @@ prompt_runner() {
 			runner_selection=""
 		fi
 
-		local runner_games
-		runner_games=$(awk -v filter="$runner_selection" -v available_runners="$available_runners" 'BEGIN { FS = ";" } {
-			if (NR == 1) { next }
-			if (filter == "") {
-				if (index(available_runners, $2) > 0) {
-				print $1;
-			}
-			}
-		else {
-			split(filter, runners, /\n/);
-			for (i in runners) {
-				if ($2 == runners[i]) {
-				print $1;
-			}
-			}
-		}
-		}' "$games_csv_path")
+		runner_games=$(get_matching_games)
+		prompt_game "$runner_games"
 		clear
 		break
 	done
-
-	prompt_game "$runner_games"
 }
 
 prompt_game() {
@@ -251,6 +288,49 @@ enumerate_runners() {
 	esac
 }
 
+get_available_runners() {
+	local unavailable_runners=""
+	for runner in $(echo -e "$SUPPORTED_RUNNERS"); do
+		if [[ ! $(enumerate_runners "$runner") ]]; then
+			local unavailable_runners="$unavailable_runners$runner"
+		fi
+	done
+
+	local available_runners=""
+	for runner in $(echo -e "$SUPPORTED_RUNNERS"); do
+		if [[ ! "$unavailable_runners" =~ $runner ]]; then
+			local available_runners
+			available_runners="$available_runners$runner\n"
+		fi
+	done
+
+	available_runners=$(echo -e "$available_runners" | sed -e '$!b' -e '/^\n*$/d')
+
+	echo "$available_runners"
+}
+
+get_matching_games() {
+	local runner_games
+	runner_games=$(awk -v filter="$runner_selection" -v available_runners="$available_runners" 'BEGIN { FS = ";" } {
+		if (NR == 1) { next }
+		if (filter == "") {
+			if (index(available_runners, $2) > 0) {
+				print $1;
+			}
+		}
+		else {
+			split(filter, runners, /\n/);
+			for (i in runners) {
+				if ($2 == runners[i]) {
+				print $1;
+				}
+			}
+		}
+	}' "$games_csv_path")
+
+	echo "$runner_games"
+}
+
 launch_game() {
 	local runner="$1"
 	local game_id="$2"
@@ -298,63 +378,6 @@ launch_game() {
 		echo "The runner $runner is not currently supported"
 		;;
 	esac
-}
-
-main() {
-	config_dir="$HOME/.config/leisure/"
-
-	disable_previews=0
-
-	if [[ "$TERM" != *"kitty"* ]]; then
-		disable_previews=1
-	fi
-
-	while getopts "c:hnv" flag; do
-		case $flag in
-		c)
-			config_dir="$OPTARG"
-			;;
-		h)
-			echo "Usage: leisure [options]"
-			echo "Options:"
-			echo "  -c <directory>          Specify a configuration directory"
-			echo "  -h                      Display this message"
-			echo "  -n                      Disable preview images"
-			echo "  -v                      Display version number"
-			exit 0
-			;;
-		n)
-			disable_previews=1
-			;;
-		v)
-			echo "Leisure $LEISURE_VERSION"
-			exit 0
-			;;
-		\?)
-			exit 1
-			;;
-		esac
-	done
-
-	games_csv_path="$config_dir/games.csv"
-
-	source "$config_dir/paths.conf" || {
-		echo "Error: No configuration file found."
-		exit 1
-	}
-
-	if ! [ -f "$games_csv_path" ]; then
-		echo "games.csv not found."
-		exit 1
-	fi
-
-	command -v fzf >/dev/null 2>&1 || {
-		echo >&2 "Error: fzf not found"
-		exit 1
-	}
-
-	prompt_media_type
-	exit 0
 }
 
 main "$@"
